groups:
  - name: reviewer
    reviewers: 2
    usernames:
      - seheonnn
      - bmryu0501
      - fepick
      - min-kim-oss
      - knujhk
<<<<<<< HEAD
      - yg654
=======
      - yg654
>>>>>>> e03741905896af892b4f0ac215f969919d592d79
